# Generated by Django 3.1.2 on 2020-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('status', models.BooleanField(verbose_name='Vendido')),
            ],
        ),
    ]
