# Generated by Django 3.1.2 on 2020-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CAMT', 'Camisetas'), ('BLUS', 'Blusinhas'), ('CAMI', 'Camisas'), ('SUCA', 'Suéteres e cardigans'), ('BLJC', 'Blazers, jaquetas e casacos'), ('COLQ', 'Coletes e quimonos'), ('REGA', 'Regatas'), ('SHBE', 'Shorts e bermudas'), ('CALC', 'Calças'), ('VEST', 'Vestidos'), ('SAIA', 'Saias'), ('MAIC', 'Meias-calças'), ('CACP', 'Cachecóis e pashminas'), ('LENC', 'Lenços'), ('BOLS', 'Bolsas'), ('SAPT', 'Sapatos'), ('MEIA', 'Meias')], max_length=300, verbose_name='Categorias'),
        ),
    ]
